# Generated by Django 3.0.3 on 2020-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analytics', '0002_visitorpagehit_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPageHitSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Global Page Hit Summary',
                'verbose_name_plural': 'Global Page Hits Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_analytics.globalpagehit',),
        ),
        migrations.CreateModel(
            name='VisitorPageHitSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Visitor Page Hit Summary',
                'verbose_name_plural': 'Visitor Page Hits Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_analytics.visitorpagehit',),
        ),
        migrations.CreateModel(
            name='VisitorSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Visitor Summary',
                'verbose_name_plural': 'Visitors Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_analytics.visitor',),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(default='', help_text='The useragent that the visitor is using.', max_length=300),
            preserve_default=False,
        ),
    ]
