# Generated by Django 3.0.3 on 2020-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analytics', '0003_auto_20200209_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='visitorpagehit',
            name='user_agent',
            field=models.CharField(default='', help_text='The useragent that the visitor is using.', max_length=300),
            preserve_default=False,
        ),
    ]
